package com.ExecutionLab.frames;

import com.ExecutionLab.utils.Generic;
import com.ExecutionLab.utils.GlobalConstants;
import com.ExecutionLab.utils.SQLLite;

import javax.swing.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Enumeration;

/**
 *
 * @author bharat.vatrapu@gmail.com
 *
 */

public class CreateProject extends javax.swing.JPanel {

    String projectPath;
    String projectType=null;
    ButtonGroup bgprojectType = new ButtonGroup();
    /**
     * Creates new form DashBoard
     */
    public CreateProject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        txtCreateProject = new javax.swing.JLabel();
        iconCreateProject = new javax.swing.JLabel();
        panelCreateProject = new javax.swing.JPanel();
        txtAccountName = new javax.swing.JLabel();
        edtAccountName = new javax.swing.JTextField();
        txtProjectName = new javax.swing.JLabel();
        edtProjectName = new javax.swing.JTextField();
        txtProjectPath = new javax.swing.JLabel();
        edtProjectPath = new javax.swing.JTextField();
        btnChooseProjectpath = new javax.swing.JLabel();
        imagePromo = new javax.swing.JLabel();
        txtProjecttype = new javax.swing.JLabel();
        rbJava = new javax.swing.JRadioButton();
        iconJava = new javax.swing.JLabel();
        rbSEMaven = new javax.swing.JRadioButton();
        iconSEMaven = new javax.swing.JLabel();
        rbhpUft = new javax.swing.JRadioButton();
        iconHp = new javax.swing.JLabel();
        txtMaven = new javax.swing.JLabel();
        txtUft = new javax.swing.JLabel();
        txtMainClass = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();
        btnNext = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        txtCreateProject.setFont(new java.awt.Font("Arial", 1, 24));
        txtCreateProject.setForeground(new java.awt.Color(102, 0, 102));
        txtCreateProject.setText("Project Setup  ");

        iconCreateProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Engineering_32px.png")));

        panelCreateProject.setBackground(new java.awt.Color(153, 204, 255));
        panelCreateProject.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        txtAccountName.setFont(new java.awt.Font("Tahoma", 1, 14));
        txtAccountName.setText("Account Name:");

        edtAccountName.setBackground(new java.awt.Color(132, 213, 243));
        edtAccountName.setFont(new java.awt.Font("Tahoma", 0, 12));
        edtAccountName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));

        txtProjectName.setFont(new java.awt.Font("Tahoma", 1, 14));
        txtProjectName.setText("Project Name:");

        edtProjectName.setBackground(new java.awt.Color(132, 213, 243));
        edtProjectName.setFont(new java.awt.Font("Tahoma", 0, 12));
        edtProjectName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));

        txtProjectPath.setFont(new java.awt.Font("Tahoma", 1, 14));
        txtProjectPath.setText("Project path:");

        edtProjectPath.setBackground(new java.awt.Color(132, 213, 243));
        edtProjectPath.setFont(new java.awt.Font("Tahoma", 0, 12));
        edtProjectPath.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));

        btnChooseProjectpath.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnChooseProjectpath.setForeground(new java.awt.Color(102, 0, 153));
        btnChooseProjectpath.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Opened_Folder_32px.png")));
        btnChooseProjectpath.setText("Choose path  ");
        btnChooseProjectpath.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 1, true));
        btnChooseProjectpath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChooseProjectpath.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102,0,102)));
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChooseProjectpath.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
            }
        });
        btnChooseProjectpath.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                btnChooseProjectpathActionPerformed();
            }
        });

        imagePromo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/create_project.jpg")));

        txtProjecttype.setFont(new java.awt.Font("Tahoma", 1, 14));
        txtProjecttype.setText("Project type:");





        rbJava.setBackground(new java.awt.Color(153, 204, 255));
        rbJava.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Java_32px.png")));
        rbJava.setText("Java main");
        rbJava.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rbJava.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
                rbJava.setBorderPainted(true);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
               // rbJava.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
                rbJava.setBorderPainted(false);
            }
            public void mouseClicked(MouseEvent e) {
                rbJava.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102,0,102)));
                rbJava.setBorderPainted(true);
            }
            public void mousePressed(MouseEvent e) {
                rbJava.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102,0,102)));
                rbJava.setBorderPainted(true);
            }
        });



        //iconJava.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Java_32px.png")));

        rbSEMaven.setBackground(new java.awt.Color(153, 204, 255));
        rbSEMaven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Selenium_32px.png")));
        rbSEMaven.setText("Maven");
        rbSEMaven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rbSEMaven.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
                rbSEMaven.setBorderPainted(true);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                // rbJava.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
                rbSEMaven.setBorderPainted(false);
            }
            public void mouseClicked(MouseEvent e) {
                rbSEMaven.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102,0,102)));
                rbSEMaven.setBorderPainted(true);
            }
            public void mousePressed(MouseEvent e) {
                rbSEMaven.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102,0,102)));
                rbSEMaven.setBorderPainted(true);
            }
        });

      //  iconSEMaven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Selenium_32px.png")));

        rbhpUft.setBackground(new java.awt.Color(153, 204, 255));
        rbhpUft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/HP_32px.png")));
        rbhpUft.setText("UFT");
        rbhpUft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rbhpUft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
                rbhpUft.setBorderPainted(true);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                // rbJava.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
                rbhpUft.setBorderPainted(false);
            }
            public void mouseClicked(MouseEvent e) {
                rbhpUft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102,0,102)));
                rbhpUft.setBorderPainted(true);
            }
            public void mousePressed(MouseEvent e) {
                rbhpUft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102,0,102)));
                rbhpUft.setBorderPainted(true);
            }
        });
        //iconHp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/HP_32px.png")));

       // txtMaven.setText("Maven");

      //  txtUft.setText("UFT");

       // txtMainClass.setText("Main class");

        bgprojectType.add(rbJava);
        bgprojectType.add(rbSEMaven);
        bgprojectType.add(rbhpUft);
        rbSEMaven.setSelected(true);

        javax.swing.GroupLayout panelCreateProjectLayout = new javax.swing.GroupLayout(panelCreateProject);
        panelCreateProject.setLayout(panelCreateProjectLayout);
        panelCreateProjectLayout.setHorizontalGroup(
                panelCreateProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelCreateProjectLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(panelCreateProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelCreateProjectLayout.createSequentialGroup()
                                                .addComponent(txtProjectPath)
                                                .addGap(18, 18, 18)
                                                .addComponent(edtProjectPath, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnChooseProjectpath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(panelCreateProjectLayout.createSequentialGroup()
                                                .addGroup(panelCreateProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(panelCreateProjectLayout.createSequentialGroup()
                                                                .addComponent(txtProjecttype)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(rbJava)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(panelCreateProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addGroup(panelCreateProjectLayout.createSequentialGroup()
                                                                                .addComponent(txtMainClass)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(txtMaven))
                                                                        .addGroup(panelCreateProjectLayout.createSequentialGroup()
                                                                                .addComponent(iconJava)
                                                                                .addGap(43, 43, 43)
                                                                                .addComponent(rbSEMaven)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(iconSEMaven)))
                                                                .addGap(38, 38, 38)
                                                                .addComponent(rbhpUft)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(panelCreateProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(iconHp)
                                                                        .addGroup(panelCreateProjectLayout.createSequentialGroup()
                                                                                .addGap(10, 10, 10)
                                                                                .addComponent(txtUft))))
                                                        .addGroup(panelCreateProjectLayout.createSequentialGroup()
                                                                .addGroup(panelCreateProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtAccountName)
                                                                        .addComponent(txtProjectName))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(panelCreateProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(edtProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(edtAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(imagePromo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(22, 22, 22))
        );
        panelCreateProjectLayout.setVerticalGroup(
                panelCreateProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelCreateProjectLayout.createSequentialGroup()
                                .addGroup(panelCreateProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelCreateProjectLayout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addGroup(panelCreateProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(panelCreateProjectLayout.createSequentialGroup()
                                                                .addGap(9, 9, 9)
                                                                .addGroup(panelCreateProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(txtAccountName)
                                                                        .addComponent(edtAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(38, 38, 38)
                                                                .addGroup(panelCreateProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(edtProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtProjectName))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(panelCreateProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(panelCreateProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(panelCreateProjectLayout.createSequentialGroup()
                                                                                        .addGap(11, 11, 11)
                                                                                        .addGroup(panelCreateProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(txtProjecttype)
                                                                                                .addComponent(rbJava)))
                                                                                .addComponent(iconJava, javax.swing.GroupLayout.Alignment.TRAILING))
                                                                        .addGroup(panelCreateProjectLayout.createSequentialGroup()
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(panelCreateProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(panelCreateProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(panelCreateProjectLayout.createSequentialGroup()
                                                                                                        .addGap(11, 11, 11)
                                                                                                        .addComponent(rbSEMaven))
                                                                                                .addComponent(iconSEMaven, javax.swing.GroupLayout.Alignment.TRAILING))
                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCreateProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(panelCreateProjectLayout.createSequentialGroup()
                                                                                                        .addGap(11, 11, 11)
                                                                                                        .addComponent(rbhpUft))
                                                                                                .addComponent(iconHp, javax.swing.GroupLayout.Alignment.TRAILING)))))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(panelCreateProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtUft)
                                                                        .addComponent(txtMaven)
                                                                        .addComponent(txtMainClass))
                                                                .addGap(67, 67, 67))
                                                        .addGroup(panelCreateProjectLayout.createSequentialGroup()
                                                                .addComponent(imagePromo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(20, 20, 20)))
                                                .addGroup(panelCreateProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(edtProjectPath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtProjectPath)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCreateProjectLayout.createSequentialGroup()
                                                .addGap(263, 263, 263)
                                                .addComponent(btnChooseProjectpath, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36))
        );

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Arrow_Pointing_Left_48px.png")));
        btnBack.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                btnBackActionPerformed();
            }
        });

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Arrow_Pointing_Right_52px.png")));
        btnNext.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                btnNextActionPerformed();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(31, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(330, 330, 330))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(btnBack)
                                                        .addGap(194, 194, 194)
                                                        .addComponent(iconCreateProject)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtCreateProject)
                                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(panelCreateProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(27, 27, 27)))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnBack)
                                        .addComponent(txtCreateProject)
                                        .addComponent(iconCreateProject))
                                .addGap(18, 18, 18)
                                .addComponent(panelCreateProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNext)
                                .addContainerGap(22, Short.MAX_VALUE))
        );
    }

    public void btnNextActionPerformed(){
        boolean flag=true;
        projectType=Generic.getSelectedRadioButtonText(bgprojectType);
        System.out.println("projectType::"+projectType);

        if(fieldValidation()){
            System.out.println("table exist::"+SQLLite.tableExists(GlobalConstants.tblPROJECTS));
            if(SQLLite.tableExists(GlobalConstants.tblPROJECTS)){
                if(SQLLite.rowExists(GlobalConstants.tblPROJECTS,"PROJECT_NAME",edtProjectName.getText())){
                    JOptionPane.showMessageDialog(null,edtProjectName.getText()+"Already Exists");
                    edtProjectName.setBackground(new java.awt.Color(255, 255, 0));
                    flag=false;
                } else  {
                    SQLLite.insertProjectsTable(edtAccountName.getText(), edtProjectName.getText(), rbSEMaven.getText(), edtProjectPath.getText());

                }
            } else {
                SQLLite.createTable(GlobalConstants.PROJECTS_SQL_TABLE);
                SQLLite.insertProjectsTable(edtAccountName.getText(), edtProjectName.getText(), rbSEMaven.getText(), edtProjectPath.getText());
            }

        } else {
            flag=false;
        }

        if(flag){
            GlobalConstants.Project_Name = edtProjectName.getText();
            Main.projectParametersSetup_frame();
        }
    }
    public void btnBackActionPerformed(){
        Main.btnProjectsActionPerformed();
    }

    public void btnChooseProjectpathActionPerformed(){
        projectPath = Generic.choosePath();
        edtProjectPath.setText(projectPath);
    }

    public boolean fieldValidation(){
        boolean flag=true;
        if(edtAccountName.getText().isEmpty() || edtProjectName.getText().isEmpty() || edtProjectPath.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Enter All Fields");
            flag =  false;
        }
        return flag;
    }




    public void rbJavaActionPerformed(java.awt.event.ActionEvent evt){
        rbJava.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102,0,102)));
        rbJava.setBorderPainted(true);
    }

//    public String getRadiovalue(){
//        String val=null;
//        if (rbJava.isSelected()) {
//            val = rbJava.getName().toString();
//        } else if (rbJava.isSelected()) {
//
//        }
//    }
    // Variables declaration - do not modify
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnChooseProjectpath;
    private javax.swing.JLabel btnNext;
    private javax.swing.JTextField edtAccountName;
    private javax.swing.JTextField edtProjectName;
    private javax.swing.JTextField edtProjectPath;
    private javax.swing.JLabel iconCreateProject;
    private javax.swing.JLabel iconHp;
    private javax.swing.JLabel iconJava;
    private javax.swing.JLabel iconSEMaven;
    private javax.swing.JLabel imagePromo;
    private javax.swing.JPanel panelCreateProject;
    private javax.swing.JRadioButton rbJava;
    private javax.swing.JRadioButton rbSEMaven;
    private javax.swing.JRadioButton rbhpUft;
    private javax.swing.JLabel txtAccountName;
    private javax.swing.JLabel txtCreateProject;
    private javax.swing.JLabel txtMainClass;
    private javax.swing.JLabel txtMaven;
    private javax.swing.JLabel txtProjectName;
    private javax.swing.JLabel txtProjectPath;
    private javax.swing.JLabel txtProjecttype;
    private javax.swing.JLabel txtUft;
    // End of variables declaration
}

